// Data produk homepage — dipakai bareng oleh app/page.js (render kartu) dan
// app/sitemap.js (image sitemap). Satu sumber supaya tidak dobel-ketik &
// tidak kelupaan update salah satu saat produk berubah.
export const products = [
  { img: 'golok-baja-carbon', alt: 'golok baja carbon untuk berkebun dan pertanian — PisauNusantara Bandung', name: 'Golok Baja Carbon', desc: 'Golok baja carbon terbaik untuk berkebun dan pertanian. Pengrajin lokal Bandung, ketajaman presisi, tahan lama untuk kebutuhan harian di ladang.', badge: 'terlaris', waText: 'Golok%20Baja%20Carbon' },
  { img: 'golok-kebun-tebas-bambu', alt: 'golok bersarung kayu ukir dengan gagang ukir kepala naga — PisauNusantara Bandung', name: 'Golok Kebun & Tebas Bambu', desc: 'Golok kebun serbaguna baja carbon untuk berkebun, menebas semak, dan tebas bambu. Bilah kuat tahan banting, gagang kayu keras, andalan petani dan pekebun.', badge: 'terlaris', waText: 'Golok%20Kebun%20%26%20Tebas%20Bambu' },
  { img: 'golok-sembelih-sapi', alt: 'golok sembelih sapi bersarung kayu ukir dengan gagang kayu — PisauNusantara Bandung', name: 'Golok Sembelih Sapi', desc: 'Golok sembelih sapi dan hewan kurban dengan bilah baja carbon sangat tajam. Panjang ideal untuk sapi dan kerbau, bilah rata sesuai syariat, kuat dan presisi.', badge: 'terlaris', waText: 'Golok%20Sembelih%20Sapi' },
  { img: 'golok-petok-cacah-tulang', alt: 'golok daging bilah lebar dengan gagang kayu dan sarung kayu, untuk cacah daging dan tulang — PisauNusantara Bandung', name: 'Golok Daging & Cacah Tulang', desc: 'Golok daging untuk cacah daging dan tulang, cocok untuk dapur maupun jagal. Bilah lebar dan berat, baja carbon tajam, mampu memotong tulang tanpa cepat tumpul.', badge: 'baru', waText: 'Golok%20Daging%20%26%20Cacah%20Tulang' },
  { img: 'pisau-berburu-professional', alt: 'pisau berburu profesional blade baja carbon untuk hunting Indonesia — PisauNusantara', name: 'Pisau Berburu Professional', desc: 'Pisau berburu profesional blade baja carbon khusus untuk hunting. Dirancang skinning dan persiapan hewan buruan, gagang tahan lembab, genggaman kuat.', badge: 'terlaris', waText: 'Pisau%20Berburu%20Professional' },
  { img: 'gagang-golok-kayu', alt: 'gagang golok kayu keras melengkung dengan alur ukir, pengganti gagang golok — PisauNusantara Bandung', name: 'Gagang Golok Kayu', desc: 'Gagang golok dari kayu keras pilihan — kuat, awet, dan nyaman digenggam. Bisa dipesan untuk golok baru maupun penggantian gagang golok lama yang sudah rusak atau oblak. Pilihan jenis kayu, model polos maupun ukir tradisional.', badge: 'baru', waText: 'Gagang%20Golok%20Kayu' },
  { img: 'sarung-golok-kayu', alt: 'sarung golok kayu sarangka dengan bilah golok baja carbon — PisauNusantara Bandung', name: 'Sarung Golok Kayu', desc: 'Sarung golok (sarangka) dari kayu keras untuk melindungi bilah golok Anda. Bisa dipesan sesuai ukuran golok, tersedia pilihan polos maupun ukir tradisional.', badge: 'baru', waText: 'Sarung%20Golok%20Kayu' },
  { img: 'kampak-pembelah-kayu', alt: 'kampak pembelah kayu berkualitas untuk outdoor dan kehutanan — PisauNusantara', name: 'Kampak Pembelah Kayu', desc: 'Kampak pembelah kayu berkualitas tinggi untuk outdoor dan kehutanan. Kepala baja tempa, gagang kokoh kuat, efisien untuk pembelahan kayu cepat.', badge: 'terlaris', waText: 'Kampak%20Pembelah%20Kayu' },
  { img: 'kujang-khas-sunda', alt: 'kujang khas sunda authentic handmade — PisauNusantara', name: 'Kujang Khas Sunda', desc: 'Kujang asli Sunda authentic handmade pengrajin Bandung. Warisan budaya Nusantara, baja berkualitas, cocok koleksi dan kostum tradisional Jawa Barat.', badge: 'terlaris', waText: 'Kujang%20Khas%20Sunda' },
  { img: 'pisau-tactical-militer', alt: 'pisau tactical militer grade untuk pertahanan diri dan outdoor Indonesia — PisauNusantara', name: 'Pisau Tactical Militer', desc: 'Pisau tactical militer grade untuk pertahanan diri dan outdoor. Blade baja high carbon, handle anti-slip ergonomis, cocok profesional dan militer Indonesia.', badge: 'terlaris', waText: 'Pisau%20Tactical%20Militer' },
  { img: 'pisau-survival-full-tang', alt: 'pisau survival full tang untuk camping dan hiking outdoor Indonesia — PisauNusantara', name: 'Pisau Survival Full Tang', desc: 'Pisau survival full tang untuk camping dan hiking outdoor Indonesia. Konstruksi full tang, blade tebal, tahan kondisi ekstrem alam liar Nusantara.', badge: 'terlaris', waText: 'Pisau%20Survival%20Full%20Tang' },
  { img: 'pisau-camping-lipat', alt: 'pisau camping lipat ringan untuk petualangan outdoor dan hiking Indonesia — PisauNusantara', name: 'Pisau Camping Lipat', desc: 'Pisau camping lipat ringan untuk petualangan outdoor dan hiking. Mudah dibawa, blade stainless berkualitas, aman untuk pemula camping dan outdoor Indonesia.', badge: 'baru', waText: 'Pisau%20Camping%20Lipat' },
  { img: 'pisau-hiking-ringan', alt: 'pisau hiking ringan untuk trail dan pendakian gunung Indonesia — PisauNusantara', name: 'Pisau Hiking Ringan', desc: 'Pisau hiking ringan untuk trail dan pendakian gunung Indonesia. Desain minimalis, bobot ringan, blade tajam, cocok pendaki gunung pemula maupun profesional.', badge: 'baru', waText: 'Pisau%20Hiking%20Ringan' },
  { img: 'arit-sawah-premium', alt: 'arit sawah premium baja carbon untuk panen dan pertanian — PisauNusantara', name: 'Arit Sawah Premium', desc: 'Arit sawah premium bahan baja carbon pilihan untuk panen dan berkebun. Gagang ergonomis kayu jati, tajam presisi, cocok petani profesional Indonesia.', badge: 'terlaris', waText: 'Arit%20Sawah%20Premium' },
  { img: 'pisau-seset-kulit-hewan', alt: 'pisau seset kulit hewan buruan profesional untuk skinning dan pengolahan daging — PisauNusantara', name: 'Pisau Seset Kulit Hewan', desc: 'Pisau seset kulit hewan buruan profesional untuk persiapan daging. Blade tipis ultra-tajam, ergonomis, mempermudah proses skinning dan pengolahan hasil buruan.', badge: 'limited', waText: 'Pisau%20Seset%20Kulit%20Hewan' },
  { img: 'cangkul-gagang-kayu-jati', alt: 'cangkul gagang kayu jati premium untuk berkebun dan pertanian Indonesia — PisauNusantara', name: 'Cangkul Gagang Kayu Jati', desc: 'Cangkul gagang kayu jati premium untuk berkebun dan pertanian. Baja tempa berkualitas, gagang jati kuat ergonomis, ideal petani dan pecinta kebun Indonesia.', badge: 'terlaris', waText: 'Cangkul%20Gagang%20Kayu%20Jati' },
  { img: 'sekop-mini-kebun', alt: 'sekop mini kebun ringan untuk berkebun urban dan taman rumahan — PisauNusantara', name: 'Sekop Mini Kebun', desc: 'Sekop mini kebun ringan untuk berkebun urban dan taman rumahan. Ukuran kompak praktis, baja berkualitas, cocok penanaman bibit dan perawatan tanaman hias.', badge: 'baru', waText: 'Sekop%20Mini%20Kebun' },
]
